### PR TITLE
feat: add recursive-get-file-info to config.py

### PR DESCRIPTION
**Pull request by westonpace**

### CODE REVIEW

**Comment by alistaire47** [comment]
Once https://github.com/voltrondata-labs/benchmarks/pull/132 is passing and you're happy with it, could you run a test build on buildkite following [the instructions here](https://github.com/voltrondata-labs/arrow-benchmarks-ci#how-can-i-test-benchmark-builds-that-run-on-buildkite-machines-ursa-i9-9960x-ursa-thinkcentre-m75q-etc) so we can tell this is going to work before we turn it on for everything? Lmk if you run into any issues

**Comment by westonpace** [comment]
@alistaire47 I don't appear to have access to https://buildkite.com/apache-arrow/arrow-bci-benchmark-build-test

**Comment by alistaire47** [comment]
Oops, it apparently doesn't work with a fork anyway. I made a copy of your changes on [a branch](https://github.com/voltrondata-labs/arrow-benchmarks-ci/tree/westonpace/feature/add-recursive-get-file-info) and used it to kick of [a build](https://buildkite.com/apache-arrow/arrow-bci-benchmark-build-test/builds/50#0188011a-001b-4ed3-8b12-b3a705079768/120-134) which kicked off a build on that machine that should run the new benchmark: https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ursa-i9-9960x/builds/2835

**Comment by alistaire47** [comment]
Never mind, that machine is backed up, so I tweaked things to still run a minimal build there, but also try on AWS to get some results without bogging things down.

ursa-i9: https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ursa-i9-9960x/builds/2836
ec2-t3: https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ec2-t3-xlarge-us-east-2/builds/2839#01880182-758b-4d82-86aa-bcd62c4083ae

**Review by alistaire47 — APPROVED** [review]
Builds passed and the results look sensible as far as I can tell. @westonpace want to take a glance at the logs and make sure you're happy? After that feel free to merge to turn this on for everybody.

**Comment by westonpace** [comment]
@alistaire47 the logs look good and the timing matches what I would expect.  I don't have write permission with this repo.  Can you merge this for me?

**Pull request merged**
